# Generated by Django 4.0.5 on 2022-06-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('page', models.IntegerField()),
                ('book_info', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshell.authors')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshell.company')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshell.genres')),
            ],
        ),
    ]
